# This file was auto-generated by bootstrap.sh
# Backend configuration for Terraform state

terraform {
  backend "s3" {
    bucket         = "photography-project-terraform-state"
    key            = "terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "photography-project-terraform-locks"
    encrypt        = true
  }
}
