#!/bin/bash

#######################################
# Terraform State Backend Bootstrap
# Project: Photography Portfolio
#######################################

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
PROJECT_NAME="photography-project"
AWS_REGION="us-east-1"
STATE_BUCKET="photography-project-terraform-state"
LOCK_TABLE="photography-project-terraform-locks"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
TERRAFORM_DIR="$PROJECT_ROOT/terraform"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  Terraform Bootstrap for ${PROJECT_NAME}${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

#######################################
# Helper Functions
#######################################

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_command() {
    if ! command -v "$1" &> /dev/null; then
        log_error "$1 is not installed. Please install it first."
        exit 1
    fi
}

#######################################
# Pre-flight Checks
#######################################

log_info "Running pre-flight checks..."

# Check for required commands
check_command "terraform"
check_command "aws"

# Check AWS credentials
log_info "Checking AWS credentials..."
if ! aws sts get-caller-identity &> /dev/null; then
    log_error "AWS credentials not configured. Run 'aws configure' first."
    exit 1
fi

AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
AWS_USER=$(aws sts get-caller-identity --query Arn --output text)
log_success "AWS credentials validated"
log_info "  Account ID: $AWS_ACCOUNT_ID"
log_info "  User/Role: $AWS_USER"
log_info "  Region: $AWS_REGION"

echo ""

#######################################
# Check if resources already exist
#######################################

log_info "Checking if state backend already exists..."

BUCKET_EXISTS=false
TABLE_EXISTS=false

# Check S3 bucket
if aws s3api head-bucket --bucket "$STATE_BUCKET" 2>/dev/null; then
    BUCKET_EXISTS=true
    log_warning "S3 bucket '$STATE_BUCKET' already exists"
fi

# Check DynamoDB table
if aws dynamodb describe-table --table-name "$LOCK_TABLE" --region "$AWS_REGION" &>/dev/null; then
    TABLE_EXISTS=true
    log_warning "DynamoDB table '$LOCK_TABLE' already exists"
fi

if [ "$BUCKET_EXISTS" = true ] && [ "$TABLE_EXISTS" = true ]; then
    log_warning "State backend already exists. Skipping Terraform apply."
    echo ""
    log_info "If you want to recreate the backend, manually delete:"
    log_info "  - S3 bucket: $STATE_BUCKET"
    log_info "  - DynamoDB table: $LOCK_TABLE"
    echo ""
    SKIP_APPLY=true
else
    SKIP_APPLY=false
fi

#######################################
# Initialize and Apply Bootstrap Terraform
#######################################

if [ "$SKIP_APPLY" = false ]; then
    log_info "Initializing Terraform in bootstrap directory..."
    cd "$SCRIPT_DIR"
    
    terraform init
    log_success "Terraform initialized"
    
    echo ""
    log_info "Creating state backend resources..."
    log_info "  S3 Bucket: $STATE_BUCKET"
    log_info "  DynamoDB Table: $LOCK_TABLE"
    echo ""
    
    # Apply with auto-approve
    terraform apply -auto-approve
    
    log_success "State backend resources created!"
    echo ""
fi

#######################################
# Create Main Terraform Directory
#######################################

log_info "Setting up main Terraform directory..."

mkdir -p "$TERRAFORM_DIR"
mkdir -p "$TERRAFORM_DIR/modules"

#######################################
# Generate backend.tf
#######################################

log_info "Generating backend configuration..."

cat > "$TERRAFORM_DIR/backend.tf" << EOF
# This file was auto-generated by bootstrap.sh
# Backend configuration for Terraform state

terraform {
  backend "s3" {
    bucket         = "$STATE_BUCKET"
    key            = "terraform.tfstate"
    region         = "$AWS_REGION"
    dynamodb_table = "$LOCK_TABLE"
    encrypt        = true
  }
}
EOF

log_success "Created backend.tf"

#######################################
# Generate main.tf (if doesn't exist)
#######################################

if [ ! -f "$TERRAFORM_DIR/main.tf" ]; then
    log_info "Creating main.tf template..."
    
    cat > "$TERRAFORM_DIR/main.tf" << 'EOF'
terraform {
  required_version = ">= 1.0"
  
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

# Your infrastructure resources will go here
# This is just a starter template
EOF
    
    log_success "Created main.tf template"
else
    log_warning "main.tf already exists, skipping"
fi

#######################################
# Generate variables.tf (if doesn't exist)
#######################################

if [ ! -f "$TERRAFORM_DIR/variables.tf" ]; then
    log_info "Creating variables.tf template..."
    
    cat > "$TERRAFORM_DIR/variables.tf" << 'EOF'
variable "project_name" {
  description = "Name of the project"
  type        = string
  default     = "photography-project"
}

variable "aws_region" {
  description = "AWS region for resources"
  type        = string
  default     = "us-east-1"
}

variable "domain_name" {
  description = "Domain name for the portfolio site"
  type        = string
  default     = "test.com"
}

variable "environment" {
  description = "Environment (dev, staging, prod)"
  type        = string
  default     = "prod"
}
EOF
    
    log_success "Created variables.tf template"
else
    log_warning "variables.tf already exists, skipping"
fi

#######################################
# Generate terraform.tfvars (if doesn't exist)
#######################################

if [ ! -f "$TERRAFORM_DIR/terraform.tfvars" ]; then
    log_info "Creating terraform.tfvars..."
    
    cat > "$TERRAFORM_DIR/terraform.tfvars" << 'EOF'
# Project Configuration
project_name = "photography-project"
aws_region   = "us-east-1"
domain_name  = "test.com"
environment  = "prod"

# Add more variables as needed for each phase
EOF
    
    log_success "Created terraform.tfvars"
else
    log_warning "terraform.tfvars already exists, skipping"
fi

#######################################
# Generate outputs.tf (if doesn't exist)
#######################################

if [ ! -f "$TERRAFORM_DIR/outputs.tf" ]; then
    log_info "Creating outputs.tf template..."
    
    cat > "$TERRAFORM_DIR/outputs.tf" << 'EOF'
# Output values for your infrastructure
# Add outputs as you build each phase
EOF
    
    log_success "Created outputs.tf template"
else
    log_warning "outputs.tf already exists, skipping"
fi

#######################################
# Generate .gitignore (if doesn't exist)
#######################################

if [ ! -f "$PROJECT_ROOT/.gitignore" ]; then
    log_info "Creating .gitignore..."
    
    cat > "$PROJECT_ROOT/.gitignore" << 'EOF'
# Terraform
**/.terraform/
**/.terraform.lock.hcl
**/terraform.tfstate
**/terraform.tfstate.backup
**/.terraform.tfstate.lock.info

# Variables (may contain secrets)
**/terraform.tfvars
**/*.auto.tfvars

# Environment files
**/.env
**/.env.local

# IDE
.idea/
.vscode/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Build artifacts
**/dist/
**/build/
**/node_modules/

# Logs
*.log
EOF
    
    log_success "Created .gitignore"
else
    log_warning ".gitignore already exists, skipping"
fi

#######################################
# Initialize Main Terraform with Remote Backend
#######################################

log_info "Initializing main Terraform with remote backend..."
cd "$TERRAFORM_DIR"

terraform init

log_success "Main Terraform initialized with remote backend!"

#######################################
# Summary
#######################################

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Bootstrap Complete! 🚀${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

log_info "State Backend Resources:"
echo "  ✓ S3 Bucket: $STATE_BUCKET"
echo "  ✓ DynamoDB Table: $LOCK_TABLE"
echo ""

log_info "Project Structure Created:"
echo "  ✓ $TERRAFORM_DIR/backend.tf"
echo "  ✓ $TERRAFORM_DIR/main.tf"
echo "  ✓ $TERRAFORM_DIR/variables.tf"
echo "  ✓ $TERRAFORM_DIR/terraform.tfvars"
echo "  ✓ $TERRAFORM_DIR/outputs.tf"
echo "  ✓ $PROJECT_ROOT/.gitignore"
echo ""

log_info "Next Steps:"
echo "  1. cd $TERRAFORM_DIR"
echo "  2. Edit terraform.tfvars with your configuration"
echo "  3. Start building your infrastructure!"
echo ""

log_success "You're ready to begin Phase 1! 🎉"
echo ""